<div>
    Welcome to Stuki.<br>
    <BR>
    <BR>
    <ul>
        <li><a href="/renderers">Manage Renderers</a></li>
        <li><a href="/plugins">Manage Plugins</a></li>
        <li><a href="/themes">Manage Themes</a></li>
        <li><a href="/attributesets">Manage Attribute Sets</a></li>

<br>

        <li><a href="/entities/view?entity_key=<?php echo $rootEntity; ?>">Entities</a></li>
        <li><a href="/search">Search Entities</a></li>
        <li><a href="/attachments/search">Search Attachments</a></li>

<br>
        <li><a href="/stuql">StuQL: Stuki Query Language</a></li>
<br>

        <li><a href="/search/reindex">Rebuild Lucene Index</a> (manually delete files first ~/application/data/Search/)</li>
        <li><a href="/search/optimize">Optimize Lucene Index</a></li>
    </ul>
</div>
