 <h2>Entity</h2>

<?php
include 'view/location.tree.phtml';
?>

<br><br>

<script>
$(function() {
    $('div#tabs').tabs();
});
</script>

<style>

form.addAttributeSet {
    border: solid;
    width: 30%;
}

</style>

<?php
include 'view/entity.insert.phtml';
?>

<br>

<a href="/entities/update?entity_key=<?php echo $entity->getKey(); ?>">
    Edit
</a>
&nbsp;&nbsp;
<?php
if (!sizeof($entity->getChildren())) {
?>
    <a href="/entities/delete?entity_key=<?php echo $entity->getKey(); ?>">
        Delete
    </a>
<?php
}
?>

<h1 style="text-align: center;" >
    <?php $entity->getTitle(); ?>
</h1>


<?php

echo "Attribute Set: " . $entity->getAttributeSet()->getName();

?>

<hr>

<?php
include 'view/details.phtml';
?>

<hr>

<?php
include 'view/references.phtml';
?>

<?php
include 'view/plugins.phtml';
?>