<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <?php

        echo $this->headLink()."\n";
        echo $this->headStyle()."\n";
        echo $this->headScript()."\n";
        echo $this->headTitle();

        ?>
    </head>

    <body>
        <div class="page">
            <div class="header">
                <a href="/entities/view?entity_key=1" id="logo"><img src="/assets/StukiLayout/images/stuki.png" alt=""/></a>

                <ul>
                    <li class="selected"><a href="/entities/view?entity_key=1">Home</a></li>
                    <li class="selected"><a href="/index/admin">Admin</a></li>

                </ul>
                <br>
                <form style="float:right;" method="get" action="/search">
                    <input size="40" type="text" name="terms">
                    <input type="submit" value="Search">
                </form>
            </div>

            <div style="clear:both;" class="body">
                <?php echo $this->get('content'); ?>
            </div>

            <div class="footer">
                <p>&#169;2012 Stuki all rights reserved.  Stuki is published under the MIT open source license.
                    <br>
                    Stuki is a product of <a href="http://www.soliantconsulting.com/">Soliant Consulting</a>.
                </p>
            </div>
        </div>
    </body>
</html>
