 <h2>Entity</h2>

<?php
include 'view/location.tree.phtml';
?>

<br><br>

<script>
$(function() {
    $('div#tabs').tabs();
});
</script>

<style>

form.addAttributeSet {
    border: solid;
    width: 30%;
}

</style>

<?php
include 'view/entity.insert.phtml';
?>

<br>
<a href="/attributesets/view?attribute_set_key=<?php echo $entity->getAttributeSet()->getKey(); ?>">
    Admin Attribute Set
</a>
&nbsp;&nbsp;

<a href="/entities/insert?parent_key=<?php echo $entity->getParent()->getKey(); ?>&attribute_set_key=<? echo $entity->getAttributeSet()->getKey(); ?>">
    Add New to Parent
    </a>
    &nbsp;&nbsp;

<a href="/entities/update?entity_key=<?php echo $entity->getKey(); ?>">
    Edit
</a>
&nbsp;&nbsp;
<?php
if (!sizeof($entity->getChildren())) {
?>
    <a href="/entities/delete?entity_key=<?php echo $entity->getKey(); ?>">
        Delete
    </a>
<?php
}
?>

<h1 style="text-align: center;" >
    <?php $entity->getTitle(); ?>
</h1>


<?php

echo "<h3>Attribute Set: " . $entity->getAttributeSet()->getName() . "</h3>";

?>

<?php
include 'view/details.phtml';
?>

<?php
include 'view/plugins.phtml';
?>

<?php
include 'view/references.phtml';
?>
