<?php echo $this->doctype() ?>
<?php
/*
 * TESTING - set display mode
 */
#$mode = "normal"; // normal/admin/user??
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php
/*
 * add jQuery common script files
 * NOTE: files added in controllers and view script load FIRST
 * then the files appended in this file are added
 * this is why I am prepending the js includes here
 */
#$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/ui/jquery.ui.core.min.js');
#$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/ui/jquery.ui.widget.min.js');
#$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/ui/jquery.ui.button.min.js');
#$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/ui/jquery.ui.datepicker.min.js');
#$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/ui/jquery.ui.autocomplete.min.js');
$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/jquery-ui.min.js');
$this->plugin('headScript')->prependFile('/assets/DefaultLayout/js/jquery.min.js');


#$this->plugin('headScript')->appendFile('/assets/DefaultLayout/js/testing.js');
#$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/testing.css');

/*
 * add jQuery common css files
 * stock jquery-ui themes
*/
$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/jquery-ui/themes/base/jquery.ui.all.css');

/*
 * the following file is a file we created by copying the original jquery.ui.css file
 * and replacing the image path with a path that is located below the images folder
 * /assets/DefaultLayout/images/override.jquery-ui/themes/smoothness/images
 */
// $this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/jquery-ui/themes/stuki/smoothness/jquery.ui.css');
#$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/jquery-ui/themes/stuki/smoothness/jquery.ui-repathed.css');

/*
 * add custom css files
*/
#$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/stuki/layout.css');
$this->plugin('headLink')->appendStylesheet('http://fonts.googleapis.com/css?family=Doppio+One');

#$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/jquery-ui/themes/stuki/base/jquery.ui.override.css');
#$this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/css/jquery-ui/themes/stuki/smoothness/jquery.ui.override.css');

// $this->plugin('headScript')->appendFile('/assets/DefaultLayout/droppy/src/javascripts/jquery.droppy.js');
// $this->plugin('headLink')->appendStylesheet('/assets/DefaultLayout/droppy/src/stylesheets/droppy.css');

echo $this->headLink()."\n";
echo $this->headTitle();
echo $this->headStyle()."\n";
echo $this->headScript()."\n";

?>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Stuki</title>
    <link rel="stylesheet" href="/assets/DefaultLayout/css/style.css" type="text/css" />
    <link rel="stylesheet" href="/assets/DefaultLayout/css/stuki.css" type="text/css" />
    <!--[if IE 7]>
        <link rel="stylesheet" href="/assets/DefaultLayout/css/ie7.css" type="text/css" />
    <![endif]-->
</head>

    <body>
        <div class="page">
            <div class="header">
                <a href="/" id="logo"><img src="/assets/DefaultLayout/images/stuki.png" alt=""/></a>
                <ul>
                    <li class="selected"><a href="/">Home</a></li>

<!--
                    <li><a href="about.html">About</a></li>
                    <li><a href="blog.html">Blog</a></li>
                    <li><a href="services.html">Services</a></li>
-->
                </ul>
            </div>
            <div class="body">
                <?php echo $this->get('content'); ?>
            </div>

            <div class="footer">
                <ul>
                    <li><a href="/">Home</a></li>
                </ul>
                <p>&#169; Copyright &#169; 2012. Stuki all rights reserved.  Stuki is published under the MIT open source license.</p>
                <div class="connect">
                </div>
            </div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17584382-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

        </div>
    </body>
</html>
