<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle(); ?>

    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery-ui.min.js"></script>

    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>

    <link rel="stylesheet" href="/css/jquery-ui/themes/smoothness/jquery.ui.css" type="text/css">
    <link rel="stylesheet" href="/css/stuki.css" title="Classic" type="text/css">

</head>
<body>
    <h1>
        <a href="/">This is Stuki
        <?php echo Stuki\Version::getVersion();?></a>
        <br>
        Environment:
        <?php echo APPLICATION_ENV; ?>
    </h1>

    <?php echo $this->raw('content'); ?>
</body>
</html>
