<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>

    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery-ui.min.js"></script>

    <link rel="stylesheet" href="/css/stuki.css" title="Classic" type="text/css">

</head>
<body>
    <h3>
    Search Layout<br />
    <a href="/">This is Stuki<?php echo Stuki\Version::getVersion();?></a><br>
	Environment:<?php echo APPLICATION_ENV; ?>
    </h3>
    <?php echo $this->raw('content'); ?>
</body>
</html>
