$(function() {

var first = '';

// Save original form dl
original = $('dl.zend_form');

// Create tab div
div = $('<div id="tabs">');
$(div).addClass('ui-tabs');
$(div).addClass('ui-widget');
$(div).addClass('ui-widget-content');
$(div).addClass('ui-corner-all');
// Wrap the form dl (already inside the form) in the div
$('dl.zend_form').wrap(div);

// Loop through all entity tabs and move form elements
// into tabs
ul = $('<ul id="item_tabs" class="subsection_tabs">');
<?php
$titles = $entity->getAttributeSet()->getTabTitles();
for ($i = 1; $i <= $entity->getAttributeSet()->getTabs(); $i++) {
?>
    $(ul).append($('<li class="tab"><a href="#tab<?php echo $i;?>"><?php echo ($titles[$i]) ?: 'Tab ' . $i; ?></a></li>'));

    tab = $('<dl class="zend_form" id="tab<?php echo $i; ?>">');

<?php
    foreach ($entity->getAttributeSet()->getAttributes() as $att) {
?>
        if (!first) first = $('dd#eav_<?php echo $att->getKey(); ?>-element').children().first();
<?php
        if ($att->getTab() == $i) {
    ?>
            $('dt#eav_<?php echo $att->getKey(); ?>-label').appendTo(tab);
            $('dd#eav_<?php echo $att->getKey(); ?>-element').appendTo(tab);
    <?php
    }
?>
<?php
    }
?>
    $('#tabs').append(tab);
<?php
}
?>

// Add save
dl_notab = $('<dl class="" id="notab">');
$('dt#save-label').appendTo(dl_notab);
$('dd#save-element').appendTo(dl_notab);

$('#tabs').append(dl_notab);
$('#tabs').prepend(ul);
// Add cancel
$('dd#save-element').append($('<span>&nbsp;&nbsp;</span>'));
$('dd#save-element').append($('<a href="#" onClick="history.back(); return false;">cancel</a>'));
// Move form description (use for global error notification)
$('dd#save-element').prepend($('p.hint'));

$('#tabs').tabs();
$(original).remove();

$(first).focus();

});
