Location Tree:<br>
<?
$parentList[] = $entity;

$last = $entity;
while ($parent = $last->getParent()) {
    if ($parent == $last) break;
    $parentList[] = $parent;
    $last = $parent;
}

$parentList = array_reverse($parentList);

$count = 0;
foreach ($parentList as $p) {
    echo '<a href="/entities/view?entity_key=' . $p->getKey() . '">' . $p->getTitle() . '</a>';
    if (sizeof($parentList) != ++$count)
        echo " >> ";
}

?>
