<h2>Insert New Renderer</h2>

<?php echo $form->render(); ?>

The default renderers are
<ul>
    <li>Renderers\Date</li>
    <li>Renderers\Decimal</li>
    <li>Renderers\EntitySelectList</li>
    <li>Renderers\Integer</li>
    <li>Renderers\Parameters</li>
    <li>Renderers\Select</li>
    <li>Renderers\String</li>
    <li>Renderers\Text</li>
</ul>


<a href="/renderers">Return to renderers</a>